config/routes.rb
MovieApp::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :sessions,only:[:new, :create, :destroy]
  resources :movies
  resources :reviews, only: [:index,:create,:destroy]

  root to: 'static_pages#home'

  match '/add', to: 'movies#new'

  match '/signup', to: 'users#new'
  match 'signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_list.html.erb
<ul class="users">
  <% @movies.each do |movie| %>
    <li class="list-group-item">
      <div class="span3">
        <%=  image_tag movie.photo.url(:small) %>
      </div>
      <div class="span7">
        <div class="large">
          <strong><%= link_to movie.name, movie %></strong>
        </div>
        <div >
          <strong>Director: </strong><%= movie.director %>
        </div>
        <div>
          <strong> Review:</strong> <%= movie.reviews.count %>
        </div>
      </div>
      <div class="span2">
        <% if signed_in? %>
          <%= link_to " Add Review", movie %>
        <% end %>

        <%  signed_in? && if current_user.admin?%>
          <%= link_to "Delete", movie, method: :delete,data: { confirm: "You sure?" } %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_movieerror.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@movie.errors.count, "error") %>.
    </div>
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_review.html.erb
<li>
<% id= review.movie_id %>
<% @movie= Movie.find_by_id(id) %>
<div class="row-fluid">
<div class="span9">

<div class="content"><%=  link_to @movie.name , @movie %></div>
 <div  class="content"><%= raw(review.comment) %></div>
  <div class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
  </div>

</div>
<div class="span3">
<div class="right">
   <% if current_user == review.user %>
   <div class="content"> <%= link_to "delete", review_path(review), method: :delete, data: { confirm: "You sure?" }%></div>
  <% end %>
  </div>
  </div>
</li>